---
# tasks file for activeDirectory

- name: Install AD
  ansible.windows.win_powershell:
    script: |
      Install-WindowsFeature AD-Domain-Services -IncludeManagementTools

- name: Check if ADDS Forest is Created
  ansible.windows.win_powershell:
    script: |
      Get-ADDomainController | Where IPv4Address -Match {{ ansible_host }}
  register: addomaincontroller

- name: Create ADDS Forest
  ansible.windows.win_powershell:
    script: |
      Import-Module ADDSDeployment
      Install-ADDSForest -CreateDnsDelegation:$false  -DatabasePath {{ paths.database }}  -DomainMode "WinThreshold"  -DomainName {{ domain }}   -DomainNetbiosName {{ netbios }} -ForestMode "WinThreshold" -InstallDns:$true -LogPath {{ paths.log }} -NoRebootOnCompletion:$true -SysvolPath {{ paths.sysvol }} -SafeModeAdministratorPassword (ConvertTo-SecureString -String {{ administrator_password }} -AsPlainText -Force)  -Force:$true
  when: not addomaincontroller.output


- name: Reboot when ADDS requires-it
  ansible.windows.win_reboot:
  when: not addomaincontroller.output

- name: Ensure each account is created
  win_domain_user:
    name: '{{ item.key }}'
    upn: '{{ item.key }}@{{ domain }}'
    password: '{{ item.value.password }}'
    password_never_expires: '{{ item.value.neverExpires }}'
  with_dict: "{{ users }}"
