---
- name: Create Script Folder
  win_file:
    path: "{{ wsus_script_folder }}"
    state: directory

- name: Create Log Folder
  win_file:
    path: "{{ wsus_log_folder }}"
    state: directory

- name: Copy WSUSClose script to machine
  win_template:
    src: wsusclose.j2
    dest: "{{ wsus_script_folder }}\\WSUSClose.ps1"

- name: Create task to run a WSUS close script
  win_scheduled_task:
    name: WSUS Close
    description: Run WSUS Close
    actions:
      - path: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
        arguments: "-ExecutionPolicy Unrestricted -NonInteractive -File \"{{ wsus_script_folder }}\\WSUSClose.ps1\""
    triggers:
      - type: daily
        start_boundary: '2019-04-01T04:00:00'
    username: SYSTEM
    run_level: highest
    state: present
